sudo: required
language: generic
dist: bionic
os:
  - linux

env:
  - PROJECT=Amlogic

before_install:
  - sudo apt-get update && sudo apt-get -y upgrade
  - sudo apt-get install -y gcc make git unzip wget xz-utils libsdl2-dev libsdl2-mixer-dev libfreeimage-dev libfreetype6-dev libcurl4-openssl-dev rapidjson-dev libasound2-dev libgl1-mesa-dev build-essential libboost-all-dev cmake fonts-droid-fallback libvlc-dev libvlccore-dev vlc-bin texinfo premake4 golang libssl-dev curl patchelf patchutils gperf lzop xfonts-utils xsltproc libjson-perl libxml-parser-perl

script:
  - PROJECT="$PROJECT" ARCH=arm DISTRO=EmuELEC make image
  - for f in repo/*; do curl --upload-file "$f" "https://transfer.sh/$f"; done
